services:
  # Frontend Service - Development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - talvyn-network
    restart: unless-stopped

  # Backend Service - Development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SMTP_SERVER=${SMTP_SERVER:-smtp-mail.outlook.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - HR_EMAIL=${HR_EMAIL:-hr@talvyntechnologies.com}
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=development
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - talvyn-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  talvyn-network:
    driver: bridge

volumes:
  uploads:
    driver: local