version: '3.8'

services:
  # Backend API Service
  backend:
    build: ./backend
    container_name: talvyn-backend
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - HR_EMAIL=${HR_EMAIL}
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - talvyn-network

  # Frontend Web Service
  frontend:
    build: .
    container_name: talvyn-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - talvyn-network

networks:
  talvyn-network:
    driver: bridge

volumes:
  backend-uploads:
    driver: local