version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - HR_EMAIL=${HR_EMAIL}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped