version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped